### PR TITLE
Map screen privacy

### LINKED ISSUE #289: Privacy does not work on Map screen and on friends view screen

### PR DESCRIPTION
**Pull request by UnavailableCode**
### Finishing the implementation of the Privacy settings
This PR fixes #289. The screens that did not take into account privacy settings before now take privacy settings into account before showing itineraries.

### Friends Finder

- When looking at someone else's profile, the itineraries will show up only if this person's privact settings allow it
- If the setttings don't allow it, you'll see the profile as if this user didn't register any trips, it doesn't tell you that their privacy settings don't allow it

### Map Screen

- Itineraries will only show up on the Map if the owner's privacy settings allow it

### CODE REVIEW

File: app/src/main/java/com/example/triptracker/view/profile/UserView.kt [hunk 1]
```diff
@@ -221,45 +220,47 @@ fun UserView(
                           Modifier.height((LocalConfiguration.current.screenHeightDp * 0.45).dp),
                       horizontalAlignment = Alignment.CenterHorizontally,
                       verticalArrangement = Arrangement.Center) {
-                        when (filteredList) {
+                        if (filteredList.isEmpty() ||
```
Comment (SpaceMercury) [inline app/src/main/java/com/example/triptracker/view/profile/UserView.kt:223]: I feel like this if statement is a bit too long, it is kind of hard to read

File: app/src/main/java/com/example/triptracker/view/map/MapOverview.kt [hunk 2]
```diff
@@ -298,7 +300,24 @@ fun Map(
             mapViewModel.getFilteredPaths(visibleRegion?.latLngBounds)
           }) {
             // Display the path of the trips on the map only when they enter the screen
```
Comment (SpaceMercury) [inline app/src/main/java/com/example/triptracker/view/map/MapOverview.kt:302]: Maybe update the comment here to account for your privacy changes

**Review by SpaceMercury — APPROVED** [review]
Overall good stuff ! Testing is missing I am going to take care of that in my next PR
